name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Running Checkstyle
        uses: dbelyaev/action-checkstyle@v0.7.4
        with:
          github_token: ${{ secrets.github_token }}
          checkstyle_config: google_checks.xml
          reporter: github-check
          level: error
          fail_on_error: false
