name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
   name: checkstyle
   runs_on: ubuntu-latest
   steps:
   - name: Check out code
     uses: actions/checkout@v2
   - name: Run Checkstyle
     uses: dbelyaev/action-checkstyle@v0.7.4
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      reporter: github-check
      level: info
      fail_on_error: true



